version: '3.8'

services:
  db:
    image: postgres:15  
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:mypassword@db:5432/my_database
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

volumes:
  pgdata:
